#!/bin/sh
set -e

# Install openlitespeed + php + mysql client
wget -O - http://rpms.litespeedtech.com/debian/enable_lst_debian_repo.sh | bash
apt -y update
apt install openlitespeed mysql-client -y
apt install lsphp70 lsphp70-common lsphp70-mysql lsphp70-opcache lsphp70-curl lsphp70-imagick lsphp70-redis lsphp70-memcached lsphp70-intl lsphp70-json -y
apt install lsphp71 lsphp71-common lsphp71-mysql lsphp71-opcache lsphp71-curl lsphp71-imagick lsphp71-redis lsphp71-memcached lsphp71-intl lsphp71-json -y
apt install lsphp70 lsphp72-common lsphp72-mysql lsphp72-opcache lsphp72-curl lsphp72-imagick lsphp72-redis lsphp72-memcached lsphp72-intl lsphp72-json -y
apt install lsphp73 lsphp73-common lsphp73-mysql lsphp73-opcache lsphp73-curl lsphp73-imagick lsphp73-redis lsphp73-memcached lsphp73-intl lsphp73-json -y
apt install lsphp74 lsphp74-common lsphp74-mysql lsphp74-opcache lsphp74-curl lsphp74-imagick lsphp74-redis lsphp74-memcached lsphp74-intl lsphp74-json -y