#!/bin/sh
set -e

# Installer
apt install -y vsftpd

# Enable Service
systemctl enable vsftpd

# Change default config
cp /etc/vsftpd.conf  /etc/vsftpd.conf_default
sed -i 's/#write_enable/write_enable/g' /etc/vsftpd.conf
sed -i 's/#xferlog_file/xferlog_file/g' /etc/vsftpd.conf
sed -i 's/#chroot_local_user/chroot_local_user/g' /etc/vsftpd.conf
sed -i 's/#chroot_list_file/chroot_list_file/g' /etc/vsftpd.conf
sed -i 's/ssl_enable=NO/ssl_enable=YES/g' /etc/vsftpd.conf
sed -i "$ i\allow_anon_ssl=NO" /etc/vsftpd.conf
sed -i "$ i\ssl_tlsv1=YES" /etc/vsftpd.conf
sed -i "$ i\ssl_sslv2=NO" /etc/vsftpd.conf
sed -i "$ i\ssl_sslv3=NO" /etc/vsftpd.conf
sed -i "$ i\require_ssl_reuse=NO" /etc/vsftpd.conf